name: Publish to NPM
on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          
      - name: Publish package on NPM 📦
        run: npm publish -w=packages/basecamp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}